replicaCount: 1

image:
  repository: 528956693660.dkr.ecr.ap-south-1.amazonaws.com/portfolio-app-dev
  tag: dev-latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  PORT: "3000"
  NODE_ENV: development

secretEnv:
  MONGO_URI:
    secretName: mongo-secret
    secretKey: MONGO_URI

ingress:
  enabled: false

resources:
  requests:
    cpu: "250m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
