replicaCount: 1

image:
  repository: 528956693660.dkr.ecr.ap-south-1.amazonaws.com/todo-app-app-prod
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  PORT: 3000
  NODE_ENV: production

secretEnv:
  MONGO_URI:
    secretName: mongo-secret
    secretKey: MONGO_URI

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - paths:
        - path: /
          pathType: Prefix


resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

